spring:
  datasource:
    url: jdbc:mysql://springaws1.cccvecappc4c.us-east-1.rds.amazonaws.com:3306/springaws1?useSSL=false&allowPublicKeyRetrieval=true
    username: crane
    password: 12345678
    driverClassName: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      dll-auto: update
    show-sql: true
    generate-ddl: true
  properties:
    hibernate:
      format_sql: true
      temp:
        use_jdbc_metadata_defaults: false

spring-aws:
  profile:
    message: RDS environment running...