spring:
  datasource:
    url: jdbc:mysql://localhost:3306/spring-aws?createDatabaseIfNotExists=true&autoReconnect=true&allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: 1234

  jpa:
    hibernate:
      dll-auto: update