spring:
  datasource:
    url: jdbc:mysql://localhost:3306/springaws?useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 1234
    driverClassName: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      dll-auto: update
    show-sql: true
    generate-ddl: true
  properties:
    hibernate:
      format_sql: true
      temp:
        use_jdbc_metadata_defaults: false

spring-aws:
  profile:
    message: Dev environment running...