spring:
  datasource:
    url: jdbc:h2:mem:springaws
    username: sa
    password:
    driverClassName: org.h2.Driver

  jpa:
    hibernate:
      dll-auto: create
    show-sql: true
    generate-ddl: true
  properties:
    hibernate:
      format_sql: true
      temp:
        use_jdbc_metadata_defaults: false

  h2:
    console:
      enable: true
      path: /h2-console

spring-aws:
  profile:
    message: QA environment running...